FROM ubuntu:22.04

RUN apt-get update && apt-get install -y \
    g++ \
    cmake \
    libgrpc++-dev \
    protobuf-compiler-grpc \
    ghostscript \
    poppler-utils \
    imagemagick \
    && rm -rf /var/lib/apt/lists/*

COPY server_cpp /app/server_cpp
COPY proto/file_processor.proto /app/server_cpp

WORKDIR /app/server_cpp

RUN protoc --grpc_out=. --cpp_out=. --plugin=protoc-gen-grpc=/usr/bin/grpc_cpp_plugin file_processor.proto \
    && cmake . && make

CMD ["./server"]
