FROM ubuntu:22.04

RUN apt-get update && apt-get install -y \
    g++ \
    cmake \
    libgrpc++-dev \
    protobuf-compiler-grpc \
    && rm -rf /var/lib/apt/lists/*

COPY client_cpp /app/client_cpp
COPY proto/file_processor.proto /app/client_cpp

WORKDIR /app/client_cpp

RUN protoc --grpc_out=. --cpp_out=. --plugin=protoc-gen-grpc=/usr/bin/grpc_cpp_plugin file_processor.proto \
    && cmake . && make

CMD ["./client"]
