FROM python:3.10-slim

COPY client_python/requirements.txt /app/client_python/
RUN pip install -r requirements.txt

COPY client_python /app/client_python
COPY proto/file_processor.proto /app/client_python

WORKDIR /app/client_python

RUN python -m grpc_tools.protoc -I. --python_out=. --grpc_python_out=. file_processor.proto

CMD ["python", "client.py"]
